language: bash
sudo: required
services:
  - docker
cache:
  directories:
  - "${HOME}/google-cloud-sdk"
before_install:
  - if [[ ! -f "${HOME}/google-cloud-sdk/bin/gcloud" ]]; then rm -rf "${HOME}/google-cloud-sdk";
    curl https://sdk.cloud.google.com | bash > /dev/null; fi
script:
- "Flow API/Bulk_Export_To_CSV_Mali_JG/ci/build.sh"
env:
  global:
  - PATH=${HOME}/google-cloud-sdk/bin:$PATH
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
